### ISSUE TITLE
Narrowing operations are underspecified

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#103]
For example, I don't know which argument is narrowed into the high lanes and which one is narrowed into the low lanes. It would be good if both the narrowing and widening operations were formalized in terms of the Python-like pseudocode used by the other operations.

**Comment by ngzhian** [comment]
I believe v8's implementation currently does:
narrow [a1,a0] [b1,b0] = [b1,b0,a1,a0]
(based on packsswb)
