### ISSUE TITLE
Agenda for Sync September sync meeting (9/24)

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#109]
It's time for another sync meeting, a few agenda items from my end.
 - Following up from last meeting, discuss end point for SIMD MVP, and possibly stop adding new instructions to the current proposal. 
 - Updates, check-ins and a timeline to push to Phase 3. 
 - Discuss changes to opcode numbering, strategy to keeping tools and implementations in sync. 

Please comment with agenda items if you have any. As always, if you don't currently attend the meeting and would like to, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) to be sent a link to the meeting.

**Comment by penzn** [comment]
I'd like to bring up #110
