### ISSUE TITLE
SIMD Sync meeting 10/22/2019 Agenda

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#121]
The next edition of this meeting will be tomorrow (10/22). Some agenda items from my end - 

- Opcode renumbering + a couple of potential late additions
- Unsigned conversions
- General updates

Please comment with agenda items if you have any. As always, if you don't currently attend the meeting and would like to, please fill out this form to be sent a link to the meeting.

**Comment by dtig** [comment]
Possibly #118, and S128 instructions that could end up on different execution units (float/int)? 
CC -  @tlively, @Maratyszcza

**Comment by dtig** [comment]
This has been moved to 10/29 as the one as scheduled coincides with the LLVM Dev meeting.

**Comment by Maratyszcza** [comment]
I'd like to discuss #125 and #122

**Comment by Maratyszcza** [comment]
And #126

**Comment by Maratyszcza** [comment]
Also #127 and #128

**Comment by dtig** [comment]
Meeting notes [linked](https://docs.google.com/document/d/1yx41xvLjkus_TctnCQe8V8HZ0j3XZ20R1qp8GU8XzAY/edit?usp=sharing). Thanks to @tlively for the taking notes. Issues that we weren't able to get to this time will be carried over to next meeting if not resolved offline by then.
