### ISSUE TITLE
simd support (neon)  for arm64-v8a?

### ISSUE THREAD

**Issue by Wuqiman** [WebAssembly/simd#139]
hello, can simd support (neon) for arm64-v8a currently?

**Comment by ngzhian** [comment]
Yes it can! Are you facing any issues with it?

**Comment by Wuqiman** [comment]
> Yes it can! Are you facing any issues with it?

hello, It's very good! Where do i go to find examples and documentation for arm64-v8a? Thank you very much~

**Comment by ngzhian** [comment]
You don't need to do anything specific to use arm64-v8a, if you run Wasm containing SIMD on a Chrome browser (with the experimental simd flag turned on) on an arm64 system, it will automatically be using NEON instructions.

**Comment by penzn** [comment]
@Wuqiman what runtime are you using? There is [implementation status doc] for a few runtimes, Also Wasmer supports SIMD, though I don't know if it works on Arm.

[is]: https://github.com/WebAssembly/simd/blob/master/proposals/simd/ImplementationStatus.md

**Comment by huqinghao** [comment]
@ngzhian For C++ codes, SIMD instructions are different  on different architectures ,i.e. using NEON on Arm and using  SSE SIMD on X86. 
> if you run Wasm containing SIMD on a Chrome browser (with the experimental simd flag turned on) on an arm64 system, it will automatically be using NEON 
 instructions.

does this means that I could just write NEON instructions on C++ codes, and it will be compiled into wasm correctly, then it can be runned on a Chrome browser on an arm64 system.
Or there are wrapped SIMD instructions provided by WASM and these instructions  can be compiled into wasm correctly. Any examples are welcomed.

**Comment by ngzhian** [comment]
Oh, I see what you mean, you will have to use the wasm simd intrinsics, like here https://emscripten.org/docs/porting/simd.html
An example of porting a project that is currently using SSE SIMD to Wasm SIMD is https://github.com/penzn/dSFMT-wasm , check out the commits to see how it was done.

**Comment by huqinghao** [comment]
Got it! Thanks you so much.
