### ISSUE TITLE
Spec interpreter

### ISSUE THREAD

**Issue by penzn** [WebAssembly/simd#141]
To track interpreter work. We have opened the first interpreter PR in #138.

**Comment by penzn** [comment]
@ngzhian has a partial change for `v128.const` which he would be able to finish after #138 gets merged. This would be needed to move forward with other functionality - memops, lane manipulations and the like depend on const for verfication.

**Comment by lars-t-hansen** [comment]
So what's the status on the interpreter?  I tried to use it to extract the spec test cases as JS, but that didn't work so well.  Should I treat this as "it's expected to work; please report a bug" or as "it's not done yet"?  (I hacked around the problem, so I'm not blocked.)

**Comment by ngzhian** [comment]
It's only slightly supported. There are multiple TODOs (search for todo v128), especially in parts to do with encoding/decoding. It's only sufficient to run a small subset of tests now. I have a pr https://github.com/WebAssembly/simd/pull/165 to add some more opcode support, it is undergoing review. If there's a specific thing you would like me to look at first, I can do that next.

**Comment by lars-t-hansen** [comment]
As I wrote, I'm not blocked on anything at the moment, just curious about what the state is.  All progress is welcome, whatever order it appears in :-)  Thanks.

**Comment by ngzhian** [comment]
This is done! Modulo bugs (maybe some cleanup, I'll do a quick grep for relevant TODOs to remove)
