### ISSUE TITLE
Handling too-large input to splat

### ISSUE THREAD

**Issue by abrown** [WebAssembly/simd#149]
When passing an `i32` to `i8x16.splat`, for example, the extra bits of the `i32` must be disposed of before they are splatted to lanes of size `i8`. The spec currently does not specify this behavior: https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#create-vector-with-identical-lanes. I had assumed that the behavior would be to truncate extra bits but I thought best to open this up for discussion, since someone may consider that retaining sign bits necessary.

**Comment by gnzlbg** [comment]
Can that be a typo? I expected `i8x16.splat(x: i8) -> v128` and `i16x8.splat(x: i16) -> v128`. 

If that is not a typo, I think that the operational semantics below are incorrect, since they assign an `i32` to a `i8` and `i16` respectively, without specifying how the value is converted. (I have no idea why would it be a good idea for these two instructions to accept an `i32`).

**Comment by abrown** [comment]
> Can that be a typo? I expected `i8x16.splat(x: i8) -> v128`...

I didn't think we could use `i8` in Wasm; I thought we were limited to `i32` and `i64`?

**Comment by penzn** [comment]
Yeah, there is no `i8` type in Wasm, only `i32`, `i64`, `f32`, `f64` (and `v128` with this proposal). We should probably fix up the python pseudocode for semantics under the description.

**Comment by abrown** [comment]
I can create a PR for this but first wanted to figure out if there are any alternate views than what I would do, which is to just truncate the 32-bit value to an 8-value disregarding sign. What do you think?

**Comment by dtig** [comment]
Maybe I'm misunderstanding, it looks like you're looking for a way to get an i8 value out of i32, why not something equivalent to a `static_cast`? These are expected to be signed values, so truncation doesn't seem correct. In cases where unsigned values are explicitly expected, they are indicates with the `_u` suffix in the opcodes.

**Comment by nfrechette** [comment]
A static_cast just truncates, it doesn't saturate to the max value in case of overflow. For values that fit within i8, truncation is fine and safe (e.g. -8) as the sign bit is extended. For larger values that don't fit (e.g. -32700), truncation will just give the bottom bits whatever they may be. I think a lot of instructions ignore extra bits and simply truncate (e.g. shift on x86) but off the top of my head I'm not sure if I remember any that saturate.

+1 for truncation from me

**Comment by dtig** [comment]
The only ones that saturate are the i8x16_{add/sub}_saturate, which explicitly specify whether signed and unsigned saturation. Same goes for the float-to-int conversions as well as the integer narrowing operations.

**Comment by abrown** [comment]
@dtig, are you for truncation as well, then?

**Comment by gnzlbg** [comment]
>  which is to just truncate the 32-bit value to an 8-value disregarding sign

Sounds good to me. Fits with what WASM already does in other operations when integers overflow their value.
