### ISSUE TITLE
Agenda for SIMD sync meeting on 12/6/2019.

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#150]
The next edition of this meeting is coming up, this time at Europe friendly time. Please respond with agenda items you would like to discuss. 

As always, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) if you would like to attend.

**Comment by mratsim** [comment]
The form mentions:
> Current meeting cadence is once a month on the 4th Tuesday 2:00PM - 3:00PM PST.

But 12/6 is on Friday tomorrow?

**Comment by dtig** [comment]
Sorry, that's confusing. That is the current cadence of the meeting with a recurring calendar incite, we're trying out a new time to be open to new contributors this time, and may change the regular cadence based on feedback. This one off meeting is scheduled for 9:00AM - 10:00AM PST (5:00PM - 6:00PM UTC).

**Comment by dtig** [comment]
I'll be cancelling this meeting due to a lack of agenda items. The next regularly scheduled edition falls on Christmas eve - will be moving that to Europe friendly time as we didn't get a chance try out a different time slot.
