### ISSUE TITLE
Agenda for SIMD sync meeting on 1/14/2020

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#174]
The next edition of this meeting is coming up, this time again at an off-cadence Europe friendly time (9:00AM - 10:00AM PST, 5:00PM - 6:00PM CET). Please respond with agenda items you would like to discuss.

As always, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) if you would like to attend.

**Comment by jan-wassenberg** [comment]
Hi, would be happy to meet the group and discuss our experience porting JPEG XL to Wasm and some proposals for additional intrinsics.

**Comment by ngzhian** [comment]
Discussion on i64x2 from/to f64x2 conversion instructions, specifically:
- i64x2.trunc_sat_f64x2_s
- i64x2.trunc_sat_f64x2_u
- f64x2.convert_i64x2_u
- f64x2.convert_i64x2_s

Implementation of these on 32-bit arch is non-obvious and expensive, potentially involving calls into runtime implementation. We can discuss how useful these are, if we missed anything in terms of implementing them, and consider removing them from the proposal.

These were added as part of https://github.com/WebAssembly/simd/issues/101. But while implementing, we found that these conversion are not optimal to have in the instruction set.

**Comment by dtig** [comment]
Some more agenda items - 
 - Broader issue of IEEE 754 compliance and inefficient codegen (As recently surfaced again in #173, and previously for Pseudo Min/Max instructions)
 - General status updates

**Comment by zeux** [comment]
I want to also briefly touch on a high level issue of codegen perf deltas - maybe a document that summarized codegen for all instructions across all archs would be useful? - as I've also hit odd cases such as "it's fast to compare integers for equality but it's slower to compare them for inequality". Or maybe we should just treat them as codegen bugs.

**Comment by lars-t-hansen** [comment]
> The next edition of this meeting is coming up, this time again at an off-cadence Europe friendly time (9:00AM - 10:00AM PST, 5:00PM - 6:00PM CET). Please respond with agenda items you would like to discuss.

9am pst is not 5pm cet, but 6pm cet.

> As always, please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) if you would like to attend.

The form says "Current meeting cadence is once a month on the 4th Tuesday ..." and today is not the fourth Tuesday.

**Comment by jan-wassenberg** [comment]
@zeux Very interesting point. We put together a spreadsheet for a performance-portable SIMD subset: 
[SIMD Operations by platform.pdf](https://github.com/WebAssembly/simd/files/4057919/SIMD.Operations.by.platform.pdf)

The original Google sheet contains comments mentioning many of the instructions used, can share via email with people who are interested.

**Comment by dtig** [comment]
> CET

Thanks for catching, updated to UTC.

The form is for the regularly scheduled meeting, the cadence of which is the same as in the form, this edition is an off cadence meeting as in the description so we can have more participation from our European members of the community, depending on feedback, we may move/alternate in the future and the form will reflect that after this meeting.

**Comment by dtig** [comment]
Thanks everyone for attending, notes for this meeting can be found [here](https://docs.google.com/document/d/1xMJe7QQPwHEx48xPFif2jS010O6X7rxkFdaJ4nVxQGg/edit?usp=sharing).
