### ISSUE TITLE
Agenda for sync meeting 03/06/2020

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#202]
The next edition of this meeting is coming up this Friday (9:00AM - 10:00AM PST/ 5:00PM - 6:00PM CET). Please respond with agenda items you would like to discuss, or bring them to the meeting. As always, please fill out this [form](https://forms.gle/9eB2ZYaziPEcTJabA) if you would like to attend.

Some agenda items on my list: 
 - Updates from in-person meeting
 - Post Phase 3 work items 
   - Discuss soft freeze on operations
 - Follow up discussion from #190 - balance of proposal being future proof vs. codegen on older intel hardware.

**Comment by arunetm** [comment]
@dtig Lets add one agenda item to discuss, 
"Criteria of Evaluation: Assessing 'broad use' and 'good modern architecture support' of ops" 

It will be great if we can discuss this before the topic on #190 above.

**Comment by dtig** [comment]
Notes from the meeting can be found [here](https://docs.google.com/document/d/1-ric8DR3uy1RWXyuoY68DCNmuRDavURHX1_UA-qSj94/edit?usp=sharing). 

As we had a few action items for different folks today, I've marked these as **TODOs**, to be followed up on either in the next meeting or in open issues. One of the action items was to add links for example design reviews, and these are in the notes. 

Some of the notes were populated offline, so please follow up with comments on the doc if something doesn't look right.

**Comment by abrown** [comment]
@dtig, one thing that the meeting today brought up was long/fast SIMD. @penzn had [proposed something](https://github.com/WebAssembly/simd/issues/29#issuecomment-566335945) a while back but I don't think I observed much feedback on it and what I heard in this meeting was that there was no clear consensus. Could we discuss a timeline for how long and fast SIMD will move forward?

**Comment by dtig** [comment]
@abrown We have a consensus on how to move forward (i.e. two separate proposals for Fast/Long SIMD in the future) - or at least we did the last time we talked about in December, just that the design space was still open - i.e. we don't have a proposal repo, or detailed discussion on what the specifics of each of those should look like. Do you mean something different by no clear consensus? 

The timeline depends on putting together an overview document with motivation, high level details of what the design would look like, and proposing it to the CG, as is standard for all Wasm proposals.

**Comment by abrown** [comment]
Ah, ok; I mean more like consensus on what @penzn proposed and whether to take that on towards the CG stuff you described. Perhaps next meeting we can talk more about his proposal?

**Comment by dtig** [comment]
Sure, we can add it to the agenda, in the mean time if you think there is value in offline discussions feel free to start that off on @penzn's exisiting github repo.
