### ISSUE TITLE
Agenda for sync meeting 04/03/2020

### ISSUE THREAD

**Issue by dtig** [WebAssembly/simd#210]
The next edition of this meeting is coming up this Friday (9:00AM - 10:00AM PDT/ 5:00PM - 6:00PM CET). Please respond with agenda items you would like to discuss, or bring them to the meeting.

If this meeting doesn't already appear on your calendar, or you are a new attendee, please fill out this [form](https://forms.gle/9eB2ZYaziPEcTJabA) to attend.

Agenda items:
 - General: Tag review, updates about next meeting editions
 - Opcode renumbering, discuss concerns in #209

**Comment by dtig** [comment]
@abrown - IIRC, the post-MVP discussion was brought up in one of the issues, is this something that you would like to discuss in this meeting?

**Comment by abrown** [comment]
Yes, specifically long SIMD: @penzn presented a proposal for this some time ago but I have not heard any feedback. I heard comments suggesting nothing had been done on this topic which was surprising since he presented it in this same meeting (I think?). Can we solicit some feedback from those who attend on this topic? @penzn, could you possibly review the basic idea?

**Comment by arunetm** [comment]
1. Poll/opposition on these concrete soft freeze criteria recommendation here: https://github.com/WebAssembly/simd/issues/203#issuecomment-597440438 

2. Future proofing the proposal allowing high cost ops that may be supported by future hw instructions?  - @dtig  do you think it makes sense to discuss your suggestion from here https://github.com/WebAssembly/simd/issues/190#issuecomment-587925967

**Comment by jlb6740** [comment]
Hi ... any update on the .bitmask instruction here https://github.com/WebAssembly/simd/pull/201 and https://bugs.chromium.org/p/v8/issues/detail?id=10308? In general, the thread https://github.com/WebAssembly/simd/pull/201 brought up discussion on the instruction count differences seen here https://github.com/zeux/wasm-simd/blob/master/Instructions.md between the two platforms. Any follow-up thoughts/ideas with regards to considerations to the spec that could help level the tilt here given phase 3.

> .

**Comment by dtig** [comment]
@arunetm For 1, we should discuss this more if there are open issues, but maybe best to have a poll on the issue instead of the meeting as not everyone contributing attends the meetings. Not sure I fully understand 2, but having a discussion sgtm!

@jlb6740 Suggested agenda items sound good, but as it's a group of people I want to make sure that this is a useful discussion. I'll leave these questions here, and we can discuss them at the meeting. 
For .bitmask operations, as you can see in the linked bug, these are in development and there is an open call for benchmarks so we can reach consensus on the linked issue when we have them. Is there something specific you are looking for there? 
For instruction count differences, we have discussed this multiple times over open issues, and in meetings before and the conclusion we have arrived to has always been that alternative semantics are hard to find, and the existing set of operations are useful for applications. While discussion is always great, it would be useful if you could bring concrete suggestions, or alternative proposals that the group can evaluate. I want to reiterate that this is not at all to discourage discussion, but an attempt to make it useful so we aren't rehashing the same discussion that's been had multiple times.

**Comment by arunetm** [comment]
Thanks. A poll on the issue sgtm for 1.

**Comment by dtig** [comment]
Notes for this meeting are linked [here](https://docs.google.com/document/d/16VnxRQetXimjBRRba8Ok_9JjwCDheqZyymwxg9iSeo8/edit?usp=sharing).
