### ISSUE TITLE
Opcode renumbering progress tracking

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#216]
We have started upating projects to use the new opcodes proposed in #209 according the process described in #129. This issue tracks the progress of the update for various projects. Feel free to comment on the progress of the update for any additional projects you may know about.

 - ✅ V8: [merged](https://chromium-review.googlesource.com/c/v8/v8/+/2173952) and available from jsvu
 - ✅ LLVM: [merged](https://reviews.llvm.org/D79224) upstream
 - ✅ Binaryen: [merged](https://github.com/WebAssembly/binaryen/pull/2820) upstream
 - ✅ WABT: released in 1.0.15
 - ✅ Emscripten: released in 1.39.15
 - ✅ wasmparser.rs: released in 0.52
 - ✅ Chrome: released to Stable in 84
 - ✅ Firefox Nightly
 - ✅ Node: Released in 14.6.
 - 📝 Rust: [LLVM PR](https://github.com/rust-lang/llvm-project/pull/56) merged, rust-lang/rust PR to follow
 - ❔ ImplementationStatus.md, BinarySIMD.md, and [tests](https://github.com/WebAssembly/simd/pull/209#issuecomment-623638499) in this repo

**Comment by abrown** [comment]
Can we add [wasmparser.rs](https://github.com/bytecodealliance/wasmparser/pull/207)?

**Comment by tlively** [comment]
Sure, what's its status right now?

**Comment by ngzhian** [comment]
Can we add [ImplementationStatus.md](https://github.com/WebAssembly/simd/blob/master/proposals/simd/ImplementationStatus.md) to the list?

**Comment by abrown** [comment]
WIP

**Comment by zeux** [comment]
Would be great to also track binary releases and dependent tools:

- Enscripten latest
- jsvu/v8 nightly (this might be ready? Unsure)
- Chrome Canary
- Chrome Stable (this will take time obviously)
- node nightly
- node stable (this will take time, as well as one above)

**Comment by dtig** [comment]
This is available in the V8 nightly version from 8.4.268 onwards, and the Chrome Canary version 84.0.4133.0 on Windows, Mac and Android (Linux, iOS still catching up). It should eventually be released to stable on Chrome 84. It looks like the latest node update was to V8 8.1.307.31, so it will take some time, but depending on ABI compatibility, it might be possible to have 8.4 in Node.js 14. Another place to try this out in Node is [node-v8](https://github.com/nodejs/node-v8) which is an automatically updated experimental version of Node.js with the V8 lkgr.

**Comment by yurydelendik** [comment]
wasmparser.rs changed the encoding in 0.52

**Comment by zeux** [comment]
Just wanted to confirm that the current status makes SIMD work end-to-end, see https://github.com/zeux/meshoptimizer/pull/141:

- Built using emscripten tot (available as a binary release via `emsdk install tot`, no need to build anything manually)
- Tested in CI using node-v8 lkgr Linux build
- Also works in Chrome Canary on Windows

Which was basically painless :)

**Comment by zeux** [comment]
node.js 14.6 supports new opcode encoding now.

**Comment by zeux** [comment]
And so does Chrome 84 (which is a release build)

**Comment by tlively** [comment]
Thanks! Updated the opening post.

**Comment by lars-t-hansen** [comment]
FWIW, so does Firefox (still Nightly-only).

**Comment by tlively** [comment]
Closing this because I am not aware of further work that needs to be done here.
