### ISSUE TITLE
NaN bits propagation rules?

### ISSUE THREAD

**Issue by juj** [WebAssembly/simd#241]
When computing e.g. `f64x2.mul` or other floating point binary operands, when both inputs are NaNs with differing bit patterns, what should the output bit pattern be? e.g. `f64x2.mul` with `0xFFFFFFFFFFFFFFFF` on the left, and `0x7FFFFFFFFFEEEEEE` on the right?

I am seeing inconsistent behavior in native vs simd when implementing SSE intrinsics to Emscripten, which also depends on LLVM optimization levels (not running under -ffast-math), so wondering if this has been specced? I was able to find general handwavy mention about nondeterminism, does this fall under that?

**Comment by abrown** [comment]
Something I was reminded of recently is that (at least in scalar Wasm which should be the same for SIMD), the NaN signing is non-deterministic: https://webassembly.github.io/spec/core/bikeshed/index.html#nan-propagation%E2%91%A0.

**Comment by arunetm** [comment]
Its useful to have nan propagation specced under SIMD as well. Non-determinism seems to be justified here to have the simd spec consistent with the core-spec. Also, relying on propagated nan behavior is arguably an app design issue. 
It helps to know if there is general consensus for a spec update.

**Comment by ngzhian** [comment]
In general SIMD float operations follow the same rules as scalar float operations, applied lane-wise.

Thus, SIMD NaN propogation should be lane-wise same as the scalar ones. Given
> e.g. f64x2.mul with 0xFFFFFFFFFFFFFFFF on the left, and 0x7FFFFFFFFFEEEEEE on the right?

Both of these are arithmetic nans, so:

> Otherwise the payload is picked non-deterministically among all arithmetic NaNs; that is, its most significant bit is 1 and all others are unspecified.

**Comment by juj** [comment]
Thanks - I'll drop testing for NaN bits in Emscripten SSE suites to resolve.
