### ISSUE TITLE
BinarySIMD.md doesn't document representation of LaneIdxN

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/simd#242]
The [SIMD instruction encodings](https://github.com/WebAssembly/simd/blob/master/proposals/simd/BinarySIMD.md#simd-instruction-encodings) table in BinarySIMD.md references LaneIdx32, LaneIdx16, etc., but doesn't define their representation anywhere.

I've been pointed to https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#immediate-operands which does mention all of these are just single bytes, but it would be useful to encode this in the binary representation document as well.

Additionally, the name in the explainer (`ImmLaneIdxN`) mismatches the one used in BinarySIMD (`LaneIdxN`), leading to further potential confusion.

**Comment by RReverser** [comment]
@ngzhian Thanks for the PR! FWIW your PR auto-closed this issue, but the last part from the description:

> Additionally, the name in the explainer (ImmLaneIdxN) mismatches the one used in BinarySIMD (LaneIdxN), leading to further potential confusion.

still remains.

**Comment by ngzhian** [comment]
Ah! #253 should fix this, thanks!
