### ISSUE TITLE
Consistency with non-trapping truncate proposal

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/simd#25]
I noticed that [the proposed non-trapping truncate instructions](https://github.com/WebAssembly/nontrapping-float-to-int-conversions/blob/master/proposals/nontrapping-float-to-int-conversion/Overview.md#design) put the `:sat` in a different place in the instruction name from [the SIMD proposal](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#floating-point-to-integer-with-saturation):
`i32x4.trunc_s/f32x4:sat` vs `i32.trunc_s:sat/f32`

I personally prefer the style of the non-trapping truncate proposal (`i32.trunc_s:sat/f32`), but mostly I'd just like for it to be consistent between the two proposals.

**Comment by rossberg** [comment]
Agreed. The latter is more consistent (though still not exactly pretty).

**Comment by stoklund** [comment]
Works for me

**Comment by dtig** [comment]
Closing in favor of the general discussion happening here - WebAssembly/spec#884.
