### ISSUE TITLE
Enable Travis CI?

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#278]
It doesn't look like Travis CI is enabled for this. I think it can be helpful while making changes to interpreter, as a check to make sure my rebases are correct. I'll be happy to set this up (it probably requires some Makefile changes to run the SIMD test case) but I don't have permissions to enable CI for this.

**Comment by binji** [comment]
I think I've set it up properly, see https://travis-ci.org/github/WebAssembly/simd/builds/712316094. Please tell me if you see an issues.

**Comment by ngzhian** [comment]
Perfect, I think the travis ci for this needs to be tweaked to have OCaml version 4.08.0, I can do that, then close this out. Thanks!

**Comment by ngzhian** [comment]
Fixed with #279
