### ISSUE TITLE
Text format for extract_lane/replace_lane literals

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#287]
For extract_lane (and similarly replace_lane or any instructions that require specifying a lane literal), the test cases allow for specifying it in terms of an `int` or `nat`:

https://github.com/WebAssembly/simd/blob/master/test/core/simd/simd_lane.wast#L889

I'm not super sure if we want this capability. Is such flexibility useful in specifying lane literals? Can we restrict it to nats? So the sign should never be there. It can only be `+` anyway.

@Honry wdyt?

**Comment by ngzhian** [comment]
Also, we seem to have two syntax errors:

- when the lane index for `i8x16.extract_lane_s` is -1, it is a parse error with "malformed lane index"
- when the lane index for `i8x16.extract_lane_s` is 16, it is a validation error with "invalid lane index"

I think we can try to be a bit more consistent here. Maybe make both parse errors, or both validation errors.
Technically -1 is parsable to be a byte of 0xff, it is then during validation that it should raise.

**Comment by tlively** [comment]
I think we should try to be as consistent as possible with the MVP spec here. My reading is that the immediate index on `local.get`, for example, can be any `u32` and can have a sign, so that suggests that the immediate index for `extract_lane` and `replace_lane` should also be allowed to have a sign. On the other hand, the local index can also be an identifier, so perhaps it is different enough that we should not try to match its rules.

**Comment by binji** [comment]
Yeah, I agree that this should be `nat` instead. I brought it up before, but it may have been missed: https://github.com/WebAssembly/simd/issues/181#issuecomment-597386919

**Comment by binji** [comment]
> My reading is that the immediate index on local.get, for example, can be any u32 and can have a sign,

@tlively I don't think that's right, an [index is either an `id` or  `u32`](https://webassembly.github.io/spec/core/text/modules.html#indices). But a [`u32` cannot have a sign](https://webassembly.github.io/spec/core/text/values.html#text-int).

**Comment by ngzhian** [comment]
> Yeah, I agree that this should be nat instead. I brought it up before, but it may have been missed: #181 (comment)

Oh nice, yea I think it was missed. Seems like we want:

- only `nat` as lane indices
- and treatment of malformed v.s. valid w.r.t https://github.com/WebAssembly/simd/issues/181#issuecomment-576003672

> @tlively I don't think that's right, an index is either an id or u32. But a u32 cannot have a sign.

I tried it out with the interpreter too, it's a parser error if we give it `local.get -1`.

**Comment by binji** [comment]
> and treatment of malformed v.s. valid w.r.t #181 (comment)

When this came up before, we still need to keep invalid vs. malformed. In particular, if the value can be represented in the binary format, then is can't be malformed, but it still can be invalid.

**Comment by ngzhian** [comment]
I imagine the binary format for lane index will be a u8, so (from @AndrewScheidecker ) "lane index < 0 || >= 256 should be malformed, but lane index < 256 && lane index >= num lanes should be invalid."

**Comment by binji** [comment]
Ah, sorry. Just realized that #181 already said that :-)

**Comment by ngzhian** [comment]
Adding some people from the discussion to see if this is an okay change, ptal, and also at #289.

@AndrewScheidecker for WAVM
@abrown for cranelift
