### ISSUE TITLE
Small rename of shuffle and swizzle

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#316]
I propose to rename `v8x16.shuffle` and `v8x16.swizzle` to `i8x16.shuffle` and `i8x16.swizzle`, this is a tiny change from `v` prefix, to `i`.

The purpose of the `v` is to indicate that we are not concerned with the underlying type. The rename does not change this fact. The purpose of the rename is to make the spec slightly simpler, and have less special cases.

If #297 happens (likely, given lack of opposition), these 2 instructions will be the only special instructions that begin with `v8x16`. If we can use `i8x16.swizzle` and `i8x16.shuffle`, it will simplify the specification slightly, since there is no need to talk about `v8x16` as a syntax.

Additionally, the rename will be consistent with other instructions, like the horizontal reductions `i32x4.all_true`, which applies the same if the instruction was `f32x4.all_true`.

**Comment by binji** [comment]
You could bring this to the SIMD group, but I'm guessing there won't be much opposition, since changing the name doesn't really affect much. Personally I think we should go ahead and make these changes now.

**Comment by penzn** [comment]
I think this only makes sense in context of the other change you are proposing, otherwise it would not be the last remaining instruction with `v8x16` name. Can we bring this up as part of the large rename, please?

**Comment by ngzhian** [comment]
@penzn "bring this up as port of the large rename" do you mean refer to this issue in the issue with the larger rename? Or bring both of these topics out at the next SIMD sync?

**Comment by penzn** [comment]
I think we should adopt the larger rename of loads and this one at the same time. I also think we should do another sync, though I doubt there would be much opposition to this changes.

**Comment by ngzhian** [comment]
Got it, in comment#1:

> If #297 happens (likely, given lack of opposition), these 2 instructions will be the only special instructions that begin with v8x16. If we can use i8x16.swizzle and i8x16.shuffle, it will simplify the specification slightly, since there is no need to talk about v8x16 as a syntax.

So if that large rename happens, then this will also happen alongside. (If the large rename happens there is even less reason this issue should be dropped.)

**Comment by penzn** [comment]
With larger rename happening there is no reason to keep the `v8x16` on shuffle and swizzle, at least in my opinion :)

**Comment by ngzhian** [comment]
> With larger rename happening there is no reason to keep the `v8x16` on shuffle and swizzle, at least in my opinion :)

I am in agreement! :)

**Comment by carlsmith** [comment]
The `shuffle` instruction doesn't really *shuffle* anything. To shuffle implies randomly mixing one set, not cherrypicking components from two.

**Comment by tlively** [comment]
@carlsmith I agree that it's not totally self documenting, but "shuffle" is standard terminology in SIMD ISAs and other SIMD-related work. For example, see clang's portable `__builtin_shufflevector` function. For users already familiar with SIMD, this is the clearest name.

**Comment by carlsmith** [comment]
@tlively - Ah, I see. That makes sense then. Sorry. Thanks for the clarification.
