### ISSUE TITLE
Memory load / store intrinsics do not mention alignment requirements

### ISSUE THREAD

**Issue by gnzlbg** [WebAssembly/simd#32]
Are these instructions aligned or unaligned load and stores ? 

That is, can I load a v32x4 from a pointer to some 32-bit value aligned to say a 4 byte boundary ? Or do these need to be aligned to a boundary with the alignment of a `v128`, let's say 16-byte boundary ?

**Comment by tlively** [comment]
@dschuff, I was actually wondering about this as well when I was writing tests for loads and stores. iirc, I just copied the other load and store tests which never had interesting alignments. Do we support alignments in LLVM?

**Comment by gnzlbg** [comment]
People often want to read e.g. 4 contiguously stored `f32`s from memory into an `v128`. I guess that a VM could track, for every pointer, the size and alignment of the allocation, and use that information when performing vector loads. Doing an "alignment" check at run-time, to decide whether to perform an aligned or unaligned load, is not worth it on any architecture, so I have my doubts that any VM will be efficiently able to perform these optimizations, or even want to incur the overhead of tracking alignment as well.

Particularly because "alignment" knowledge often acts at a distance. For example, whether memory is aligned or not is often known by programmers writing higher-level language code: e.g. one allocates `v128`s, casts a `v128` pointer to an `f32` pointer, and "know" that the memory referenced by that pointer allows `v128` aligned loads. The actual loads and store can happen in code that's far away, where the VM only sees that an `f32` pointer is casted to a pointer to `v128` and that's it.

**Comment by sunfishcode** [comment]
The alignment field is there, in the [`memarg` immediate field](https://webassembly.github.io/spec/core/bikeshed/index.html#syntax-memarg) in the load and store instructions in the proposal. As with the scalar loads and stores, this alignment field is a *hint*, and not a guarantee -- all wasm loads and stores always work when unaligned, with any hint value, but may go slow if the hint value is greater than the actual runtime address.

**Comment by gnzlbg** [comment]
@sunfishcode how does a code generator (e.g. like cranelift) use this information to generate aligned / unaligned vector loads ?

**Comment by lemaitre** [comment]
> The alignment field is there, in the [`memarg` immediate field](https://webassembly.github.io/spec/core/bikeshed/index.html#syntax-memarg) in the load and store instructions in the proposal. As with the scalar loads and stores, this alignment field is a _hint_, and not a guarantee -- all wasm loads and stores always work when unaligned, with any hint value, but may go slow if the hint value is greater than the actual runtime address.

If the alignment is a hint and not a guarantee, how can you expect any speed up if the hint is a correct?
You would either need to generate the slow path code (unaligned access), or have a condition to take the fastest considering the hint was actually true.
The former gives no benefit compared to no hint at all, and the latter would be actually slower.

However, if it is a guarantee (meaning if it is not fulfilled, anything can happen: just working or crashing are examples), then you could generate the fastest access considering the required alignment with absolutely no overhead.

If you're not sure about the alignment, just specify the minimum alignment possible: 1.
Any extra information about the minimal alignment of your data should only make things better, not worse.

**Comment by binji** [comment]
> You would either need to generate the slow path code (unaligned access), or have a condition to take the fastest considering the hint was actually true.

The original rationale is described here: https://github.com/WebAssembly/design/blob/73cb0e6e379e473071533f14437e1516dd7e94c8/Semantics.md#alignment
> Alignment affects performance as follows:
> * Aligned accesses with at least natural alignment are fast.
> * Aligned accesses with less than natural alignment may be somewhat slower (think: implementation makes multiple accesses, either in software or in hardware).
> * Misaligned access of any kind may be massively slower (think: implementation takes a signal and fixes things up).

**Comment by gnzlbg** [comment]
@binji that rationale does not really answer the question. 

If the alignment is a hint, and the hint is incorrect (the memory address passed is not a multiple of the alignment), and the code generator issues an aligned store to generate a fast path where it should have issued an unaligned store, then the behavior of the program is pretty much undefined (i hope that on most targets you would get a trap).

If the code generator needs to issue a run-time check (which an optimizing code generator might be able to avoid in some cases, but in general, AFAICT, any address can be passed to a load, so it has to be checked at run-time), to verify whether the alignment hint is correct or not, then nowadays you might as well always do unaligned memory accesses which will often be faster than a check + an aligned memory access.

**Comment by sunfishcode** [comment]
@gnzlbg There are two main implementation strategies, and which one is best depends on the hardware and the VM:
 - Just use unaligned instructions always (eg. movups). This works great on hardware where unaligned instructions are fast when given aligned instructions at runtime. Essentially, the hardware is doing the runtime alignment check for us. Many popular hardware architectures do this today, and it seems to be the trend. Or:
 - Use aligned instructions, and have a VM that catches signals and fixes things up in the case where an address isn't actually aligned.

The main use for the hint is: If a hint specifies a lower alignment, we can split the access into multiple accesses and then shuffle the bits into a single value. This can be much faster than taking a signal when using the second strategy above, or when unaligned accesses are slow on the underlying platform (some platforms take a signal and handle it in the OS).

**Comment by lemaitre** [comment]
@sunfishcode What you describe with signal catching should not be considered valid implementation for a "hint" alignment.
For most people, when you specify a hint, and the hint is not correct, you should not get any slower than without (or at least not by much).
But trapping is very expensive and should not be considered a normal run path.

What you describe is more a guaranteed alignment, but runtime failure of this alignment is somehow recoverable (but really expensive).
Also, the use-case for the hint is also covered if the specified alignment is guaranteed and not a hint.

The only interesting bit with the hint is if you could patch the assembly code after a signal to handle a lower alignment without overhead for the rest of the execution.

**Comment by lemaitre** [comment]
@gnzlbg I understand all that. But what I meant is: if there is a huge penalty when the hint is not respected, then it should not be called an hint.
The fact that you can recover from misaligned access is fine. But this should really not be viewed as a normal execution path.

As I just said, I would be fine with this if the first misaligned access would patch the generated code to handle a lower alignment for future accesses.
But I don't know if this is something planned, or even desirable for the WASM VM.

Also, no human will write WASM by hand, but some will write using intrinsics (if they are provided at some point).
And the question about alignment will arise again for intrinsics: the compiler might lose information the developer knows.

**Comment by gnzlbg** [comment]
Turns out that the spec already has load / stores taking `memarg`. It just wasn't clear to me from reading it that `memarg` was the alignment, duh, I've updated #34 to make it clear that `memarg` is an immediate mode argument, and referenced `memarg` to the scalar part of the wasm spec.

**Comment by sunfishcode** [comment]
"Hint" is the word the wasm spec uses. In that context it's jargon for "semantically irrelevant". I can see how it can be misleading though.

However, the approach of taking a signal and fixing up the value is valid, and it's even mentioned in the design documents @binji quoted above: "Misaligned access of any kind may be massively slower (think: implementation takes a signal and fixes things up)."

The strategy you mention of patching the code dynamically would be valid too, though I haven't heard of any engines doing that. To my knowledge, the majority of wasm code today is generated by compilers that have relatively reliable information about alignment.
