### ISSUE TITLE
Agenda for Sync meeting 09/04/20 (?)

### ISSUE THREAD

**Issue by penzn** [WebAssembly/simd#323]
Not to take over from @tlively, just that there is no issue for the upcoming sync, but I'd like to bring up some agenda items.

The times and the invite form are (probably) similar to the previous meetings, for example see #293 

Some ideas for agenda:

- Rename of loads (#297) and minor rename of shuffles (#316)
- Spec and interpreter progress - looks like a good amount of work has gone in, would be interesting to hear about it

**Comment by ngzhian** [comment]
Some more suggestions, mostly about suggestions of additional instructions

- #232 prototype is done, has results, I think we can vote on whether to include this
- #122 prototype is done, has results, can also vote on this

@Maratyszcza

**Comment by tlively** [comment]
Thanks, @penzn! We haven't had a sync in a long time, so I agree that there are a bunch of small things to catch up on.

**Comment by lars-t-hansen** [comment]
I'd welcome a chance to discuss the pending opcodes, both those @ngzhian brings up and the others (dot product, load zero).  And perhaps to touch on how we know when we're done adding opcodes for the MVP.

**Comment by tlively** [comment]
Maybe we can take a vote on raising the bar for accepting new opcodes again.

**Comment by tlively** [comment]
Just a reminder that this meeting is tomorrow at 9:00AM - 10:00AM PDT/ 5:00PM - 6:00PM CET, so please post any additional agenda items you would like to discuss.

If this meeting doesn't already appear on your calendar, or you are a new attendee, please fill out this [form](https://forms.gle/9eB2ZYaziPEcTJabA) to attend.

**Comment by lars-t-hansen** [comment]
> Just a reminder that this meeting is tomorrow at 9:00AM - 10:00AM PDT/ 5:00PM - 6:00PM CET, so please post any additional agenda items you would like to discuss.

9AM PDT is (still / for the time being) 6PM CET.

**Comment by lars-t-hansen** [comment]
> Maybe we can take a vote on raising the bar for accepting new opcodes again.

And perhaps discuss triaging existing issues and decide which to move to post-mvp.

**Comment by tlively** [comment]
Oops, sorry about the timezone mixup!

**Comment by tlively** [comment]
Thanks for a very productive meeting everyone! Here are the [notes](https://docs.google.com/document/d/138cF6aOUa9RZC2tOR7AhlIQWdmX5EtpzXRTVDAN3bfo/edit?usp=sharing).
