### ISSUE TITLE
Running JS tests for SIMD

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#330]
SIMD is not exposed to JS, it is defined to raise exceptions when accessed from JS world. Instantiating a module that exports a function with V128 in its signature is an error.

So that means that we can't generate JS files in the interpreter (the workaround is to [skip it](https://github.com/WebAssembly/simd/blob/master/test/core/run.py#L95)). That's not ideal though - JS test scripts can be useful for testing, e.g. web engines can run their implementation against those tests.

I'm filing this issue to try and get ideas on how to generate the JS test files for SIMD.

Here's how the SIMD tests are currently written (not that different from other tests):

1. a module which defines a bunch of exported functions, one for each SIMD instruction to test
1. a bunch of `assert_return` calls which calls those functions

From this text format, JS is generated:

1. the module is translated to using the JS API to instantiate module in binary format
1. `assert_return` translates into calling the exported functions, passing in the relevant args

As described earlier, for SIMD tests, just the first step, instantiating the module will fail. This suggests that **when generating JS output from SIMD tests**, we might want to wrap up any v128 functions into something JS understands, like arrays. For that we can use multi-value.

So, a test like this:

```wast
(module
  (func (export "eq")
    (param $x v128) (param $y v128)
    (result v128)
    (i32x4.eq (local.get $x) (local.get $y)))
)
(assert_return (invoke "eq" (v128.const i32x4 0xFFFFFFFF 0xFFFFFFFF 0xFFFFFFFF 0xFFFFFFFF)
                            (v128.const i32x4 0xFFFFFFFF 0xFFFFFFFF 0xFFFFFFFF 0xFFFFFFFF))
                            (v128.const i32x4 -1 -1 -1 -1))
```

wrap `eq` such that semantically it is equivalent to:

```wast
(module
  ;; define v128_of_4_i32 that takes i32 -> i32 -> i32 -> i32 -> v128
  ;; exported function name is the same, but has a different signature
  (func (export "eq")
    (param $x1 i32) (param $x2 i32) (param $x3 i32) (param $x4 i32)
    (param $y1 i32) (param $y2 i32) (param $y3 i32) (param $y4 i32)
    (result i32) (result i32) (result i32) (result i32)
    (i32x4.eq
      (call v128_of_4_i32
        (local.get $x1)
        (local.get $x2)
        (local.get $x3)
        (local.get $x4))
      (call v128_of_4_i32
        (local.get $y1)
        (local.get $y2)
        (local.get $y3)
        (local.get $y4))
    ))
)

;; and all the caller becomes
(assert_return (invoke "eq"
  (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF)
  (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF) (i32.const 0xFFFFFFFF))
  (i32.const -1) (i32.const -1) (i32.const -1) (i32.const -1)
```

(I don't know what the exact syntax for multiple results is, but this is the idea).

Suggestions very welcome. Thanks!

**Comment by tlively** [comment]
Using multivalue for returns and splitting up the parameters makes a lot of sense to me. But rather than transforming the test functions, it might make sense to generate and export wrappers functions that take care of marshaling and unmarshaling the vectors but delegate to the original functions for everything else. That way the tests still properly check that vectors can be used as function parameters and returns.

How are you planning to do these code transformations? If it would be ok to take a dependency on an external tool, it would be trivial to write a Binaryen pass to do this.

**Comment by ngzhian** [comment]
> How are you planning to do these code transformations? If it would be ok to take a dependency on an external tool, it would be trivial to write a Binaryen pass to do this.

Probably just in the reference interpreter. I did a bit more digging, it seems like it has such a capability already, which it uses for f32, f64, i64 https://github.com/WebAssembly/simd/blob/master/interpreter/script/js.ml#L266.
Let me take a closer look.

**Comment by ngzhian** [comment]
I've been hacking around, it looks like what exists in js.ml is sufficient for my needs, closing this.

**Comment by lars-t-hansen** [comment]
FWIW, I wrote a one-off script to translate the spec tests to JS some time back, output here: https://hg.mozilla.org/mozilla-central/file/tip/js/src/jit-test/tests/wasm/simd/spec.  The resulting code does almost everything in wasm, returning an int to JS.  In other (hand-written) tests I usually go through memory: JS sets up values in memory, wasm loads them, calls the test function, stores the result, JS reads and checks result.

**Comment by binji** [comment]
@ngzhian Sounds like you went this direction anyway, but I agree that it's best to stick with how the reference interpreter does it for `i64` types. I'm not too concerned about checking that v128 values work as params/results, since that can (and should) be tested explicitly with `call` instructions.
