### ISSUE TITLE
Shorten all saturating instructions to "sat"

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#332]
The [saturating instructions](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#saturating-integer-arithmetic) spell out the word "saturate".
I propose we shorten it to "sat" to be consistent with the truncation with saturation instructions, see https://webassembly.github.io/spec/core/text/instructions.html, e.g. 𝗂𝟨𝟦.𝗍𝗋𝗎𝗇𝖼_𝗌𝖺𝗍_𝖿𝟥𝟤_𝗌.

**Comment by carlsmith** [comment]
I always thought `lop` and `sop` would have been better names for `truncate` and `saturate`, especially in an assembly language, but that kind of thing isn't really appropriate in a serious standard.

`+1` for `sat`.

**Comment by tlively** [comment]
@penzn @abrown Does this sound good to you? I think this is straightforward enough that it probably doesn't need to be voted on in a meeting.

**Comment by penzn** [comment]
Sounds fine to me, and I don't think we need to vote unless there are any concerns about this.

**Comment by binji** [comment]
Let's keep this issue open while we fix other WAT consumers too (e.g. binaryen, wabt). I'm also curious what we should do with the clang intrinsics. From the meeting last week, it sounds like we should batch these changes and do them all at once, is that right?

**Comment by tlively** [comment]
Yes, batching changes is always nice for Binaryen and LLVM, and I think it's ok if they lag behind a bit on the renaming. I separately opened #342 to discuss further changes to the intrinsic names.

**Comment by ngzhian** [comment]
wabt is done https://github.com/WebAssembly/wabt/pull/1553, llvm and wasm_simd128.h is not up to date.

**Comment by ngzhian** [comment]
LLVM is updated, closing.
