### ISSUE TITLE
How to check if SIMD web-assembly is supported by the browser?

### ISSUE THREAD

**Issue by Zelex** [WebAssembly/simd#337]
I imagine the test would be similar to https://stackoverflow.com/questions/47879864/how-can-i-check-if-a-browser-supports-webassembly ?

**Comment by penzn** [comment]
The test should be loading a Wasm module with at least one SIMD instruction in it.

**Comment by ngzhian** [comment]
You can also try using this library https://github.com/GoogleChromeLabs/wasm-feature-detect/ which internally does what penzn described.

**Comment by Zelex** [comment]
Thanks!
