### ISSUE TITLE
When should our next Sync meeting be?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#402]
Friday, December 18 is a day off for Google

Friday, December 25 is Christmas

Friday, January 1 is New Years

Friday, January 8 is free but a long way away.

I propose that we next meet on January 8, but try to make progress online in the meantime. Specifically, we should aim to have benchmarking data for all of the outstanding proposals by the January 8th meeting. How does that sound to everyone?

cc @lars-t-hansen @arunetm @abrown @Maratyszcza @omnisip @dtig @rrwinterton

**Comment by omnisip** [comment]
Do we have an expected timeline for finishing all of the prototypes?  I'm going to be home for the holidays, so if I have some spare cycles, I can probably help benchmark other proposals too.

**Comment by Maratyszcza** [comment]
I'm fine with meeting on Dec 18

**Comment by tlively** [comment]
There are a lot of moving parts, so I don't have a good overall picture. @ngzhian, do you have a sense of when V8 prototyping will be done for the outstanding instructions? (Or would you say it's done right now?) On the tools side, I aim to get up to parity with V8 within the next week.

Another alternative meeting time (suggested by Deepti) would be the 22nd during the normal CG meeting slot, assuming the CG meeting is canceled, which [looks likely](https://github.com/WebAssembly/meetings/issues/685). This is my favorite idea so far.

**Comment by dtig** [comment]
I'm fine with meeting on the 18th, but we could also do the 14th or the 22nd - the 22nd pushes pretty close to the holidays, but as the CG meeting that day will most likely be cancelled it's possibly a slot that most people may have empty on their calendars.

**Comment by dtig** [comment]
Oops, added a comment before the page updated, but what @tlively said. :)

**Comment by arunetm** [comment]
22nd works for me too :)

**Comment by lars-t-hansen** [comment]
I'm not working on the 22nd so won't be able to attend then (18th is my last day before the holidays).  I don't think that's a good reason not to meet; I'm OK with reading the minutes.

**Comment by ngzhian** [comment]
> do you have a sense of when V8 prototyping will be done for the outstanding instructions?

All these instructions have been prototyped for at least 1 arch on V8:

- load store lane
- prefetch
- saturating q-format mul
- i64x2.widen_{low,high}
- extending miul
- popcnt
- extending pairwise add
- i64x2.eq
- i64x2.bitmask
- signselect

If I'm missing prototype on some opcodes please cc me on the issue so I get some visibility, thanks!

**Comment by Maratyszcza** [comment]
@ngzhian #383 are missing

**Comment by omnisip** [comment]
And #395

**Comment by penzn** [comment]
I am off on 22nd as well, though I might dial in if I am going to be around my desk (cannot promise), I am also OK with reading the minutes later.

I would like to eventually discuss #403, but we would definitely need larger group for that.

**Comment by tlively** [comment]
Ok, lets save #403 for January, then. How about @Maratyszcza and I try to get as much benchmarking as possible by the 22nd for the instructions prototyped in V8 and we can focus that meeting on evaluating whether those newly benchmarked instructions should be included in the proposal. Would the folks who are going to be out on the 22nd (@lars-t-hansen, @penzn) be ok with that?

**Comment by lars-t-hansen** [comment]
Yes.

**Comment by penzn** [comment]
Same here, I think we should discuss prefetch with everybody present.

**Comment by tlively** [comment]
Here are the [notes](https://docs.google.com/document/d/1Tnf-fvRcCVj_vv8CjAN_qUvj4Wa57JnPa8ghGi4_C-s/edit?usp=sharing) from this morning's meeting. We had two provisional votes that achieved consensus: one to include the load/store lane instructions (#350) and one to include the i64x2 widening instructions (#290). Unless the folks who weren't in the meeting today have objections, we will merge these instructions after our next meeting.
