### ISSUE TITLE
Using existing SIMD intrinsics

### ISSUE THREAD

**Issue by penzn** [WebAssembly/simd#41]
I would like to ask a question separate from #31. There is a slide in [May 2017 CG deck](https://github.com/WebAssembly/simd/blob/master/proposals/simd/WebAssembly-SIMD-May-2017.pdf) that mentions using hardware intrinsics headers when targeting WASM SIMD (the one titled "SIMD Programs"):

> • Existing sources using <x86intrin.h> or <arm_neon.h>
> • Portable code using vector extensions
> • Auto-vectorizers

Looks like at some point there was anticipation that hardware intrinsics would be compiled to WASM. Was there any further development of this idea? I could not find a good answer in the issues.

**Comment by tlively** [comment]
Yes, @rrwinterton has expressed interest in implementing existing interfaces (e.g. xmmintrin.h) for wasm. I don't know whether he has any concrete implementation plans, but he would be blocked on me implementing the `__builtin_wasm_*` functions. Once those builtin functions are implemented in clang, he or anyone else would be able to implement xmmintrin.h, x86intrin.h, arm_neon.h, or any other interface in terms of them.

**Comment by dtig** [comment]
Looks like nothing more needs to be done here, closing.
