### ISSUE TITLE
Notifying wider CG of intent to vote for phase 4 soon

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#420]
As @dtig suggested in our meeting today, we should notify the wider CG about our intent to call for a phase 4 vote sometime soon. I suggest that we give a short presentation at the next CG meeting covering the work we've done and the instructions we've added recently as well as what we still intend to evaluate before a final vote. @dtig, is that along the lines of what you had in mind?

Does anyone have anything in particular that they want to bring to the CG's attention?

**Comment by dtig** [comment]
Thanks @tlively, this is along the lines of what I had in mind. The presentation at the next CG, with advance notice of intent of going to Phase 4, and a poll at the following meeting with a final operation set makes sense to me.

**Comment by ngzhian** [comment]
[Presented](https://docs.google.com/presentation/d/1XhyAmMW5aT4pxxpDoHIYgXCDH209kubN5ph8s9I9lhc/edit#slide=id.p) at the 2021-01-19 CG meeting.
