### ISSUE TITLE
Tracking instructions with unassigned opcodes

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#421]
We don't want to do another full renumbering, but we also want to choose reasonable opcodes for new instructions, so we decided [here](https://github.com/WebAssembly/simd/pull/406#issuecomment-755575762) and in the [1/8/21 meeting](https://docs.google.com/document/d/1jb8ICiyIqgHGVq8MswgRIFGXec69wGmKePitOgcvq50/edit#heading=h.n7rdjckrtpe5) that beginning with #376, the final opcodes of all newly merged instructions will be decided after we finalize the instruction set. The opcodes of instructions merged earlier than #376 will not change.

Here is a (hopefully up-to-date) list of instructions whose opcodes will need to be finalized:

 - Extended multiplications (#376)
 - Load/store lane instructions (#350)
 - i64x2 widening instructions (#290)
 - Saturating rounding Q-format multiplication (#365)
 - i64x2.bitmask (#368)

**Comment by Maratyszcza** [comment]
A couple more:
- `v128.any_true` instruction to replace `i8x16.any_true`/`i16x8.any_true`/`i32x4.any_true`/`i64x2.any_true` (#416)
- Potentially floating-point rounding instructions, as their opcodes overlap with 64-bit `min`/`max` reserved opcodes

**Comment by ngzhian** [comment]
Closing, this is done, and superseded by #452
