### ISSUE TITLE
Ambiguous compare semantics

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#45]
The proposal says "The comparison operations all compare two vectors lane-wise, and produce a mask vector with the same number of lanes as the input interpretation." Does each lane in the result have a value of either 0 or 1 or a value of either 0 or -1 (all zeroes or all ones)?

cc @billbudge @dtig

**Comment by dtig** [comment]
The values in the lanes are all 0s or all 1s. For example, for  `i32x4.gt_s(a: v128, b: v128) -> v128`,
If the lane in a, is greater than the one in b, the result is set to all 1s. This would be equivalent to the `pcmpgtd` instruction on Intel, or the `vcgt` instruction on ARM.

**Comment by gnzlbg** [comment]
The "Operations" section of the proposal states:

> Comparison operators produce a mask vector where the bits in each lane are 0
for false and all ones for true:

I've sent a PR (#47) to state this in the "Comparison" subsection as well.
