### ISSUE TITLE
Rename integer-to-integer widening instructions to "extend"?

### ISSUE THREAD

**Issue by ngzhian** [WebAssembly/simd#467]
Referring to this section https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-to-integer-widening, was there a reason why we chose "widen"? That isn't a terminology used in the current Wasm spec, it uses "extend" (e.g. see https://webassembly.github.io/spec/core/appendix/index-instructions.html).

Can we change the names to extend? (Everything else stays the same, only `s/widen/extend/`.

**Comment by tlively** [comment]
SGTM

**Comment by zeux** [comment]
If we switch from `widen` to `extend`, what do we do with `narrow`? Doesn't look like scalar spec has an equivalent.

**Comment by tlively** [comment]
The scalar spec has `i32.wrap_i64`, but `wrap` isn't great for the SIMD version because it saturates rather than wrapping :/

**Comment by ngzhian** [comment]
We can keep narrow since there is no equivalent instruction in scalar spec.

**Comment by tlively** [comment]
There were no strong objections to this renaming at today's meeting. @ngzhian, do you want to put a PR together?
