### ISSUE TITLE
Agenda for sync meeting 2/19/21

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/simd#470]
The next meeting will be Friday, February 19 at 9:00AM - 10:00AM PST/ 6:00PM - 7:00PM CET. Please respond with agenda items you would like to discuss.

If this meeting doesn't already appear on your calendar, or you are a new attendee, please fill out this [form](https://forms.gle/9eB2ZYaziPEcTJabA) to attend.

Agenda so far:

* Final opcodes (#452)
* Renaming the widen instructions (#467) (if not resolved by meeting time)

**Comment by tlively** [comment]
Thanks for opening this, @lars-t-hansen! I updated the opening post with the usual information.

**Comment by dtig** [comment]
We should also talk about the long standing issue about documenting performance guidelines - specifically what and how it should be documented, and where it should live.

**Comment by arunetm** [comment]
It will be helpful if we can talk about a process for post MVP feature extensions.

**Comment by penzn** [comment]
Another suggestion is instruction cost discussion (#404) - we were supposed to get to it in #410, but I don't think we did.

**Comment by tlively** [comment]
Thanks everyone! Here are the [notes](https://docs.google.com/document/d/11xg9uWyRc7QyafBntSKF9FDD05DVg3ZUaXINE4zi7aQ/edit#)
