### ISSUE TITLE
Immediate lane indices for {extract,replace}_lane

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#49]
I assume this was discussed somewhere that I haven't found, but what was the rationale for making the lane indices immediates? I ask because LLVM allows for variable lane indices, so code generation could be simplified if we also allowed for variable lane indices.

**Comment by penzn** [comment]
At least part of the reason is that the hardware only supports immediate indices (please correct me if ARM does though). Are there other backends that only take immediate lane indices?

**Comment by penzn** [comment]
For example, x86 backends have to deal with that as well.
