### ISSUE TITLE
Meeting Registration: SIMD Monthly Triage meeting

### ISSUE THREAD

**Issue by arunetm** [WebAssembly/simd#63]
We are planning to have a sync to triage the issue backlog. Please fill out this [form ](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) to be sent a link to the triage meeting.

**Comment by dtig** [comment]
Meeting notes for this meeting (01/22/2018) are [linked here](https://docs.google.com/document/d/1QkPK9mnwMXPoWwKRZYMRySPgJzMMfnQ2skw5ORR06gI/edit?usp=sharing). Fill this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) for details about upcoming meetings.

**Comment by dtig** [comment]
The next edition of this meeting is happening tomorrow, fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) to join in.

**Comment by gnzlbg** [comment]
It might be nice to set up the monthly meeting a bit sooner in advance, and maybe try to survey the timezones of those that want to attend and consider that when setting up the meeting time.

**Comment by dtig** [comment]
We had that with the first edition of this meeting in January, and the time was decided on based on a survey back then. Let me edit the form to accept more information so that folks can respond with time zone concerns. I'll send out an FYI maybe the week before so new attendees have enough time to plan to attend.

**Comment by arunetm** [comment]
The 4th sync is planned for tomorrow 2PM PST. Please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSfCbRJXnTjDJw5Ei6k5M4vzj1VAr34_Jg_W4bKbqpj3ZMfaeA/viewform) to join. 

If the current time slot is inconvenient, please mark the appropriate response on the form and we will find a better time slot for future meetings.
