### ISSUE TITLE
Intrinsic Header file added to clang compiler for WebAssembly

### ISSUE THREAD

**Issue by rrwinterton** [WebAssembly/simd#64]
We are in the process of creating an header file that would be maintained by the clang compiler tool for WebAssembly to generate intrinsics.  This header file will work for the platforms supported the clang compiler targeting WebAssembly.  The header fill base implementation will be presented to the working group in the next few weeks.  The unit tests for the WebAssembly intrinsics are also being created and are still up for discussion on who will maintain the unit tests.  It will be based of the emscripten clang compiler integration is the first thought as more of the users of the SIMD intrinsics will be like to need other functionality like STL.  But this should be discussed.

**Comment by arunetm** [comment]
@rrwinterton do we need any followup on this issue?

**Comment by gnzlbg** [comment]
FYI the Rust standard library added a module to the std lib last summer doing the same. We had a discussion about naming with some people implementing it in LLVM here: https://github.com/rust-lang-nursery/stdsimd/issues/562 Might be worth it to get on the same page about naming.

**Comment by tlively** [comment]
The header and tests are being worked on in an upstream branch of emscripten. You can follow along here: https://github.com/emscripten-core/emscripten/tree/wasm-simd-intrinsics

**Comment by tlively** [comment]
We have a PR! Please review and comment at https://github.com/emscripten-core/emscripten/pull/8559. Once we have decided on a final set of intrinsics, we can update the documentation at https://github.com/WebAssembly/tool-conventions/pull/108 and also get this header into clang for use outside of emscripten.

**Comment by dtig** [comment]
The header file has landed thanks to Thomas, so closing this issue.
