### ISSUE TITLE
July sync agenda

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#85]
Please comment with agenda items you would like to discuss at this month's meeting, taking place on Tuesday, July 23 at 2pm pacific time.

**Comment by tlively** [comment]
I think it would be fair to cancel if we have no agenda items by end of day today.

**Comment by arunetm** [comment]
Yes agree.

**Comment by tlively** [comment]
I'd say it's safe to cancel this one. Feel free to comment if there's anything we should remember to discuss next month!
