### ISSUE TITLE
SIMD proposal backwards compatibility

### ISSUE THREAD

**Issue by nlewycky** [WebAssembly/simd#87]
We're planning to ship SIMD support in our WASM implementation. Looking at other implementations, it looks like wabt has SIMD behind an --enable-simd flag while WAVM has SIMD enabled by default with no flag. Would it cause a problem for the standardization of SIMD if there's a body of existing implementations and .wasm files out there that is using pre-standard extensions? I was hoping there could be some documentation that provides guidance for implementors.

**Comment by tlively** [comment]
The guidance you're looking for is in the standardization [process document](https://github.com/WebAssembly/meetings/blob/master/process/phases.md). Features are generally safe to ship during stage 4. Since SIMD is only in stage 2 right now, it should not be considered stable and I would recommend against shipping it by default without good reason.

**Comment by syrusakbary** [comment]
> Features are generally safe to ship during stage 4. Since SIMD is only in stage 2 right now, it should not be considered stable and I would recommend against shipping it by default without good reason

Sounds good! Is there any reason is turned on by default on WAVM @AndrewScheidecker ?

We were thinking on doing:

```shell
wasmer run simd_example.wasm --backend=llvm
```

versus:

```shell
wasmer run simd_example.wasm --backend=llvm --enable-simd
```

**Comment by arunetm** [comment]
Keeping the feature under a flag until its stable enough has the benefit of helping potential users to easily recognize it as experimental/non-stable feature, and potentially avoid building dependencies until its released as stable.

**Comment by AndrewScheidecker** [comment]
> Is there any reason is turned on by default on WAVM @AndrewScheidecker ?

Not really; I think it makes sense to gate it behind an option.

**Comment by dtig** [comment]
Looks like there's general consensus - closing this issue.
